@TodoApi_HostAddress = https://localhost:7064

GET {{TodoApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{TodoApi_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "walk dog",
  "isComplete": true
}

###
